[package]
name = "gpl-nft-voter"
version = "0.1.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "gpl_nft_voter"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
solana-program = "1.9.5"
anchor-lang = { version = "0.22.1", features = ["init-if-needed"] }
spl-governance = { version = "2.2.2", features = ["no-entrypoint"] }
spl-governance-addin-api  = "0.1.1"
anchor-spl = "0.22.1"
mpl-token-metadata = { version = "1.1.0", features = ["no-entrypoint"] }

[dev-dependencies]
solana-sdk = "1.9.5"
solana-program-test = "1.9.5"
spl-token = { version = "^3.3.0", features = ["no-entrypoint"] }

borsh = "0.9.1"
spl-governance-tools=  "0.1.2"