[workspace]
members = [
    "programs/gateway",
    "programs/quadratic",
    "programs/realm-voter",
    "programs/nft-voter",
    "programs/bonk-plugin",
    "programs/token-haver",
    "programs/token-voter",
]

[profile.release]
overflow-checks = true